CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'iustoglu'@'%' IDENTIFIED BY '123';
GRANT ALL PRIVILEGES ON wordpress.* TO 'iustoglu'@'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'root123';
